const nombreGaleria = "paisajes";
const tipoGaleria = "fotos";
const galeriaActual = [

    "../FOTOSVIDEOS/paisajes/paisajes-01.jpg",
    "../FOTOSVIDEOS/paisajes/paisajes-02.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-03.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-04.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-05.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-06.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-07.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-08.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-09.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-10.JPG",
      "../FOTOSVIDEOS/paisajes/paisajes-11.JPG",
      "../FOTOSVIDEOS/paisajes/paisajes-12.JPG",
      "../FOTOSVIDEOS/paisajes/paisajes-13.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-14.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-15.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-16.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-17.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-18.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-19.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-20.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-21.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-22.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-23.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-24.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-25.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-26.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-27.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-28.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-29.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-30.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-31.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-32.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-33.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-34.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-35.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-36.JPG",
      "../FOTOSVIDEOS/paisajes/paisajes-37.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-38.JPG",
      "../FOTOSVIDEOS/paisajes/paisajes-39.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-40.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-41.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-42.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-43.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-44.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-45.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-46.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-47.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-48.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-49.jpg",
      "../FOTOSVIDEOS/paisajes/paisajes-50.jpg",
    "../FOTOSVIDEOS/miarte/miarte-51.jpg"

];
